/**
 * Pressy Admin API
 * Cœur du système pressy
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import IHttpClient from "../IHttpClient";
import { inject, injectable } from "inversify";
import { IAPIConfiguration } from "../IAPIConfiguration";
import { Headers } from "../Headers";
import HttpResponse from "../HttpResponse";

import { ArticleDto } from '../model/articleDto';
import { CreateArticleRequestDto } from '../model/createArticleRequestDto';
import { TYPES } from "../variables";


@injectable()
export class ArticlesService {
    
    @inject(TYPES.IApiHttpClient) private httpClient: IHttpClient;
    @inject(TYPES.IAPIConfiguration) private APIConfiguration: IAPIConfiguration;
    get basePath(): string {
        return this.APIConfiguration.basePath || 'https://pressy-admin-api-dev.herokuapp.com/v1';
    }

    /**
     * 
     * 
     * @param request 
     
     */
    public async articleCreateArticle(request: CreateArticleRequestDto, headers?: Headers): Promise<ArticleDto>;
    public async articleCreateArticle(request: CreateArticleRequestDto, headers?: Headers): Promise<HttpResponse<ArticleDto>>;
    public async articleCreateArticle(request: CreateArticleRequestDto, headers: Headers = {}): Promise<any> {
        if (!request){
            throw new Error('Required parameter request was null or undefined when calling articleCreateArticle.');
        }

        // authentication (Bearer) required
        if (this.APIConfiguration.apiKeys["Authorization"]) {
            headers['Authorization'] = this.APIConfiguration.apiKeys["Authorization"];
        }
        headers['Accept'] = 'application/json';
        headers['Content-Type'] = 'application/json';

        let response = await this.httpClient.post(`${this.basePath}/article`, request , headers);
        return response.response;
    }


    /**
     * 
     * 
     
     */
    public articleGetAllArticles(headers?: Headers): Promise<Array<ArticleDto>>;
    public articleGetAllArticles(headers?: Headers): Promise<HttpResponse<Array<ArticleDto>>>;
    public async articleGetAllArticles(headers: Headers = {}): Promise<any> {
        // authentication (Bearer) required
        if (this.APIConfiguration.apiKeys["Authorization"]) {
            headers['Authorization'] = this.APIConfiguration.apiKeys["Authorization"];
        }
        headers['Accept'] = 'application/json';

        let response = await this.httpClient.get(`${this.basePath}/article`, headers);
        return response.response;
    }

}
