/**
 * Pressy Admin API
 * Cœur du système pressy
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Observable } from "rxjs/Observable";
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/toPromise';
import IHttpClient from "../IHttpClient";
import { inject, injectable } from "inversify";
import { IAPIConfiguration } from "../IAPIConfiguration";
import { Headers } from "../Headers";
import HttpResponse from "../HttpResponse";

import { MemberInfoDto } from '../model/memberInfoDto';
import { TYPES } from "../variables";


@injectable()
export class MembersService {
    
    @inject(TYPES.IApiHttpClient) private httpClient: IHttpClient;
    @inject(TYPES.IAPIConfiguration) private APIConfiguration: IAPIConfiguration;
    get basePath(): string {
        return this.APIConfiguration.basePath || 'http://localhost:3002/v1';
    }

    /**
     * 
     * 
     
     */
    public memberGetAllMembers(observe?: 'body', headers?: Headers): Observable<Array<MemberInfoDto>>;
    public memberGetAllMembers(observe?: 'response', headers?: Headers): Observable<HttpResponse<Array<MemberInfoDto>>>;
    public memberGetAllMembers(observe: any = 'body', headers: Headers = {}): Observable<any> {
        // authentication (Bearer) required
        if (this.APIConfiguration.apiKeys["Authorization"]) {
            headers['Authorization'] = this.APIConfiguration.apiKeys["Authorization"];
        }
        headers['Accept'] = 'application/json';

        const response: Observable<HttpResponse<Array<MemberInfoDto>>> = this.httpClient.get(`${this.basePath}/member`, headers);
        if (observe === 'body') {
               return response.map(httpResponse => httpResponse.response);
        }
        return response;
    }

    public memberGetMember(id: number, observe?: 'body', headers?: Headers): Observable<MemberInfoDto>;
    public memberGetMember(id: number, observe?: 'response', headers?: Headers): Observable<HttpResponse<MemberInfoDto>>;
    public memberGetMember(id: number, observe: any = 'body', headers: Headers = {}): Observable<any> {
        // authentication (Bearer) required
        if (this.APIConfiguration.apiKeys["Authorization"]) {
            headers['Authorization'] = this.APIConfiguration.apiKeys["Authorization"];
        }
        headers['Accept'] = 'application/json';

        const response: Observable<HttpResponse<Array<MemberInfoDto>>> = this.httpClient.get(`${this.basePath}/member/${id}`, headers);
        if (observe === 'body') {
            return response.map(httpResponse => httpResponse.response);
        }
        return response;
    }

}
