/**
 * Pressy Admin API
 * Cœur du système pressy
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 
 */
export interface CreateSlotRequestDto { 
    /**
     * 
     */
    startDate: Date;
    /**
     * 
     */
    type: CreateSlotRequestDto.TypeEnum;
    /**
     * 
     */
    availableDrivers: number;
}
export namespace CreateSlotRequestDto {
    export type TypeEnum = '1' | '2';
    export const TypeEnum = {
        _1: '1' as TypeEnum,
        _2: '2' as TypeEnum
    }
}
