/**
 * Pressy Admin API
 * Cœur du système pressy
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CreateAddressRequestDto } from './createAddressRequestDto';
import { CreateOrderItemRequest } from './createOrderItemRequest';
import { CreateSlotRequestDto } from './createSlotRequestDto';


/**
 * 
 */
export interface EditOrderRequestDto { 
    /**
     * 
     */
    id: number;
    /**
     * 
     */
    type?: EditOrderRequestDto.TypeEnum;
    pickupSlot?: CreateSlotRequestDto;
    deliverySlot?: CreateSlotRequestDto;
    address?: CreateAddressRequestDto;
    /**
     * 
     */
    items?: Array<CreateOrderItemRequest>;
    /**
     * 
     */
    memberId?: number;
}
export namespace EditOrderRequestDto {
    export type TypeEnum = '0' | '1';
    export const TypeEnum = {
        _0: '0' as TypeEnum,
        _1: '1' as TypeEnum
    }
}
