/**
 * Pressy Admin API
 * Cœur du système pressy
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AddressDto } from './addressDto';
import { DriverInfoDto } from './driverInfoDto';
import { MemberInfoDto } from './memberInfoDto';
import { OrderItemDto } from './orderItemDto';
import { SlotDto } from './slotDto';


/**
 * 
 */
export interface OrderDto { 
    /**
     * 
     */
    id: number;
    /**
     * 
     */
    type: OrderDto.TypeEnum;
    pickupSlot: SlotDto;
    deliverySlot: SlotDto;
    address: AddressDto;
    /**
     * 
     */
    items: Array<OrderItemDto>;
    driver: DriverInfoDto;
    member: MemberInfoDto;
}
export namespace OrderDto {
    export type TypeEnum = '0' | '1';
    export const TypeEnum = {
        _0: '0' as TypeEnum,
        _1: '1' as TypeEnum
    }
}
